name: Install in conda env
on:
  push:
    paths:
    - '**.py'
    - '.github/workflows/ci.yml'
jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'macos-latest', 'windows-latest']
        # os: ['windows-latest']
        # python-version: [3.5, 3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: 3.9
      - name: install and list packages
        shell: pwsh
        run: |
          conda install -c conda-forge rdkit 
          conda list
      - name: run test
        shell: pwsh
        run: |
           python rdkit-smarts-tests.py --prefix ${{ matrix.os }}
      - uses: actions/upload-artifact@v2
        with:
          name: outfiles
          path: outputs/
          retention-days: 5
